run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  fast: false
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - copyloopvar
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  nlreturn:
    block-size: 3

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"

    - linters:
        - errcheck
      text: "Error return value of `d.Set` is not checked"

    - linters:
        - gosec
      text: "G501:"

    - linters:
        - gosec
      text: "G404:"
