secrets:
  - id: private-key
    statement: false-positive in description field
    paths:
      - selectel/resourse_selectel_secretsmanager_certificate_v1.go

vulnerabilities:
  - id: GO-2026-5932
    statement: |
      False positive: The vulnerability is inside the deprecated subpackage golang.org/x/crypto/openpgp,
      which is not imported or used by our code. Trivy triggers on the parent module golang.org/x/crypto due to 
      module-level resolution.
