name: Acceptance Tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        # NOTE: to update the version, use `make pin-sha-tags`.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        # NOTE: to update the version, use `make pin-sha-tags`.
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26"

      - name: Set up Terraform
        # NOTE: to update the version, use `make pin-sha-tags`.
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false

      - name: Run test
        run: make testacc
        env:
          OS_DOMAIN_NAME: ${{ secrets.OS_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_AUTH_URL: ${{secrets.OS_AUTH_URL}}
          OS_REGION_NAME: ${{secrets.OS_REGION_NAME}}
